version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-brave_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/brave:1.82.172@sha256:7228f2212b6a241462bf3ad43cead909be362f1e8496554d18868214369a8194
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    security_opt:
      - no-new-privileges:true
    ports:
      - 3577:3001
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"