version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-brave_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/brave:1.80.122@sha256:2b8dd50d1e2aeaaf3f292bb95424329f5ac461f217758b95980a5f53a2a6a3f6
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    security_opt:
      - no-new-privileges:true
    ports:
      - 3577:3001
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"