version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-qbittorrent_server_1
      APP_PORT: 8096

  server:
    image: lscr.io/linuxserver/qbittorrent:5.1.2@sha256:d6aebe87050274db1e80b54ed8be5684836d57698fbc840e29df24ef0471cf12
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8096
      - TORRENTING_PORT=35114
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 35114:35114
      - 35114:35114/udp
    restart: unless-stopped
