version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-zorinos-core_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:zorinos-core@sha256:af1b0c56c29c3e022ad621dc49a5bfa602c2a934412185078ded150c334ac47c
    security_opt:
      - seccomp:unconfined
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"