version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-zen_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/zen:1.7.6b@sha256:afd1232a972ef9cba1b6e6516bd042a1f6ecd5eb60ed5feb6d3cf104ed4ea14c
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"