version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tibor309-zen_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/zen:1.14.5b@sha256:2713597e7e8b16b0a82ae2398b8e014b0df8f2ed40450ee6c4884804406bde6d
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"